@@ -1,13 +1,7 @@
title: Auburn Warr # your name (or website title) here
logo: "Headshot.jpg" # your photo (or logo) here
description: > A GIS Analyst with a strong enthusiasm for Lord of the Rings
  <a href="https://www.linkedin.com/in/auburn-w-740a12100/">View My LinkedIn Profile</a> 
